### ISSUE TITLE
java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by 5HT2** [MrPowerGamerBR/TemmieWebhook#6]
```
com/github/kevinsawicki/http/HttpRequest
[20:33:10] [Thread-20/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:   at com.mrpowergamerbr.temmiewebhook.TemmieWebhook$1.run(TemmieWebhook.java:24)
[20:33:10] [Thread-20/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:   at java.lang.Thread.run(Thread.java:748)
```
doesn't work in my final jar, works fine when I run it in a dev env

**Comment by 5HT2** [comment]
Added that to my gradle, works.
